### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by bkonkle** [mzp/docker-bucklescript#1]
Hi! Thanks for sharing this Dockerfile! I'm trying to get a Reason/BuckleScript Express project up and running, and I get the following error when trying to build an image:

```
Step 6/12 : RUN npm install -g bs-platform
 ---> Running in caacbd076ce5
/usr/bin/bsb -> /usr/lib/node_modules/bs-platform/lib/bsb
/usr/bin/bsrefmt -> /usr/lib/node_modules/bs-platform/lib/bsrefmt
/usr/bin/bsc -> /usr/lib/node_modules/bs-platform/lib/bsc

> bs-platform@2.1.0 postinstall /usr/lib/node_modules/bs-platform
> node scripts/install.js

fs.js:766
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EACCES: permission denied, rename '/usr/lib/node_modules/bs-platform/vendor/ninja-build/ninja.linux64' -> '/usr/lib/node_modules/bs-platform/lib/ninja.exe'
    at Object.fs.renameSync (fs.js:766:18)
    at setUpNinja (/usr/lib/node_modules/bs-platform/scripts/install.js:70:12)
    at Object.<anonymous> (/usr/lib/node_modules/bs-platform/scripts/install.js:161:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
```

Here's my Dockerfile in its entirety:

```docker
FROM ocaml/opam:debian

USER root

ENV NODE_ENV=production

# Install OCaml toolchain
RUN opam update && \
  opam switch 4.02.3+buckle-master && \
  echo "eval `opam config env`" > /etc/profile.d/opam.sh && \
  rm -rf /home/opam/opam-repository

# Install Nodejs toolchain
RUN (curl -sL https://deb.nodesource.com/setup_8.x | bash -) && \
  apt-get install -y nodejs yarn --no-install-recommends && \
  apt-get clean && \
  rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

RUN npm install -g bs-platform

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn

# Bundle app source
COPY . .

CMD [ "yarn", "start" ]
```

Any help would be greatly appreciated!

**Comment by mzp** [comment]
hmm, i'll try it.
